---
apiVersion: v1
kind: Service
metadata:
  name: crawler
  labels:
    app: project
    component: crawler
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: project
    component: crawler
