---
apiVersion: v1
kind: Service
metadata:
  name: mongohost
  labels:
    app: project
    component: mongohost
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: project
    component: mongohost
