---
apiVersion: v1
kind: Service
metadata:
  name: rabbithost
  labels:
    app: project
    component: rabbithost
spec:
  type: NodePort
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: project
    component: rabbithost
